# See the tutorial at: https://dev.to/ahmedash95/simple-steps-to-dockrize-your-laravel-app-4h40
version: '2'
services:
  webserver:
    image: nginx:alpine
    volumes:
      - ./site:/var/www
      ## copy nginx configuration for our application ##
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      ## set the port to run the webserver on ##
      - "${HOST_PORT_HTTP}:80"
    networks:
      - cloudways_test_network
      
  app:
    ## read php image from our custom docker image ##
    build:
      context: .
      dockerfile: ./docker/php/${PHP_VER}/Dockerfile
      args:
        ENV_NAME: ${ENV_NAME}
        PHP_VER: ${PHP_VER}
    volumes:
      ## copy project files to /var/www ##
      - ./site:/var/www
    working_dir: /var/www
    tty: true
    restart: unless-stopped
    networks:
      - cloudways_test_network

  db:
    image: 'mysql/mysql-server:8.0'
    ## expose the mysql port to our machine so we can access it from any mysql-client like TablePlus ##
    ports:
      - "${DB_CONTAINER_PORT}:3306"
    ## keep mysql data on localhost so we don't lose them ##
    volumes:
      - ./docker-volumes-data/db:/var/lib/database
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - cloudways_test_network

  redis:
    image: redis
    volumes:
      ## keep redis data on localhost so we don't lose them ##
      - ./docker-volumes-data/redis:/data
    networks:
      - cloudways_test_network

  wpdemo:
    image: wordpress:latest
    links:
      - db:mysql
    #volumes_from:
    #  - wpdata
    ports:
      - "${MORDPRESS_PORT}:80"
    environment:
      - WORDPRESS_DB_NAME=${DB_DATABASE}
      - WORDPRESS_DB_USER=SamuraiAdmin
      - WORDPRESS_DB_PASSWORD=konnichiwa75
    networks:
      - cloudways_test_network

  pmademo:
    image: "phpmyadmin:latest"
    links:
      - db:mysql
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    links:
      - db:db
    depends_on:
      - db
    restart: always
    networks:
      - cloudways_test_network

networks:
  cloudways_test_network: